services:
  baza_base:
    container_name: baza_base
    build: .
    ports:
      - 8001:8001
    command: bash -c "alembic upgrade head && gunicorn --workers=3 -b 0.0.0.0:8001 -k uvicorn.workers.UvicornWorker main:app"
    environment:
      APP_NAME: "baza_base"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env_prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
volumes:
  postgres_data:


